# Generated by Django 3.0.2 on 2020-01-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('GL', 'Geistesleben'), ('RL', 'Rechtsleben'), ('WL', 'Wirtschaftsleben')], max_length=2)),
                ('dt_added', models.DateTimeField(auto_now_add=True)),
                ('people', models.ManyToManyField(to='relations.Person')),
            ],
        ),
    ]
