# Generated by Django 3.0.2 on 2020-02-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_itemcollection'),
        ('relations', '0003_auto_20200129_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='collections',
            field=models.ManyToManyField(to='categories.ItemCollection'),
        ),
    ]
