# Generated by Django 3.0.2 on 2020-02-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0005_player_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
