# Generated by Django 3.0.2 on 2020-02-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_auto_20200202_1855'),
        ('users', '0004_auto_20200203_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='collections',
            field=models.ManyToManyField(default=None, to='categories.ItemCollection'),
        ),
    ]
