# Generated by Django 3.0.2 on 2020-02-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200203_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='collections',
        ),
    ]
