# Generated by Django 2.2 on 2020-03-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('participant', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('call_time', models.DateTimeField()),
                ('call_log', models.CharField(choices=[('d', 'Dialed'), ('r', 'Received')], max_length=1)),
                ('duration', models.TimeField()),
            ],
        ),
    ]
