# Generated by Django 3.0.2 on 2020-02-10 12:35

from django.db import migrations, models
import sk.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dt_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dt_added', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now_add=True)),
                ('suggest_until', models.DateTimeField(blank=True, default=sk.models.default_suggest_time)),
                ('vote_until', models.DateTimeField(blank=True, default=sk.models.default_vote_time)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('dt_voted', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
