# Generated by Django 3.0.2 on 2020-02-09 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dt_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('dt_added', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('suggestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sk.Suggestion')),
            ],
        ),
    ]
