# Generated by Django 3.0.2 on 2020-02-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='suggestions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sk.Suggestion'),
        ),
    ]
