# Generated by Django 3.0.2 on 2020-02-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0002_auto_20200209_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='suggestions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sk.Suggestion'),
        ),
    ]
