# Generated by Django 3.0.2 on 2020-01-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=60)),
                ('parent_cat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
        ),
    ]
