# Generated by Django 3.0.2 on 2020-01-24 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dt_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 10, 44, 56, 801890)),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
