# Generated by Django 3.0.2 on 2020-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200124_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dt_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
