# Generated by Django 3.0.2 on 2020-02-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('items', models.ManyToManyField(to='categories.Item')),
            ],
        ),
    ]
