# Generated by Django 3.0.2 on 2020-02-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_itemcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
