# Generated by Django 3.0.2 on 2020-02-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_item_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='filepath',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='filename',
            field=models.CharField(default='', max_length=30),
        ),
    ]
